name: Slow Tests

on:
  schedule:
    - cron: "30 3 * * 1"   # weekly, Mon 03:30 UTC
  workflow_dispatch:

jobs:
  slow:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }
      - run: |
          python -m pip install -U pip
          pip install -e ".[dev]" || pip install .
          pip install pytest
      - name: Run slow tests
        env: { PYTHONWARNINGS: error }
        run: pytest -m slow -q
